#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo pavithra

# Get log and store it into text file -12345
git log -1 --shortstat > data/history_log.txt
#Send store file to RevPro
curl -X POST --data "@history_log.txt" "https://webhook.site/44f4555e-d1b4-4ec9-bd61-e4db2de9d303"

